name: ai_slide_content
description: "AI slide content widget."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  cupertino_icons: ^1.0.8
  firebase_ai: ^3.2.0
  flutter:
    sdk: flutter
  rfw: ^1.0.31
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
